# ! This is deprecated. all frontend asset building is now on nginx Dockerfile.production
FROM node:24-alpine3.21 AS vue-builder

WORKDIR /var/www/html

# Copy package.json and package-lock.json files
COPY ./nodejs_app/vuejs/package*.json ./

# Copy the rest of the application code
COPY ./nodejs_app/vuejs .

# Install all dependencies for building the app
RUN npm ci

# Build the React application
RUN npm run build

# Install only production dependencies
RUN npm ci --only=production
